org.gradle.jvmargs=-Xmx1G
minecraft_version=1.21.1
neo_version=21.1.12

parchment_mapping_version=2024.07.28
parchment_mc_version=1.21

mod_version=1.0.1
maven_group=com.falaut.kubejsnaturesaura
archives_base_name=kubejs_naturesaura
mod_id=kubejs_naturesaura
mod_name=KubeJS Nature's Aura
mod_author=FalAut

kjs_ver=2101.7.0-build.131
rhino_ver=2100.2.5-build.46
arch_ver=13.0.6