modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL="https://github.com/FalAut/KubeJS-Natures-Aura/issues"
license = "MIT"

[[mods]]
modId = "kubejs_naturesaura"
version = "${version}"
displayName = "KubeJS Nature's Aura"
logoFile="icon.png"
authors="FalAut"
description = '''
KubeJS Nature's Aura
'''

[[dependencies.kubejs_naturesaura]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs_naturesaura]]
modId = "kubejs"
type = "required"
versionRange = "[2004.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs_naturesaura]]
modId = "naturesaura"
mandatory = true
versionRange = "[40.1,)"
ordering = "NONE"
side = "BOTH"