modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL="https://github.com/FalAut/KubeJS-Natures-Aura/issues"
license = "MIT"

[[mods]]
modId = "kubejs_naturesaura"
version = "${version}"
displayName = "KubeJS Nature's Aura"
logoFile="icon.png"
authors="FalAut"
description = '''
KubeJS Nature's Aura
'''

[[dependencies.kubejs_naturesaura]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs_naturesaura]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs_naturesaura]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs_naturesaura]]
modId = "naturesaura"
mandatory = true
versionRange = "[39.4,)"
ordering = "NONE"
side = "BOTH"